services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - '${NGINX_PORT:-8080}:80'
        depends_on:
            - app
            - db
        container_name: nginx
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: backend
        depends_on:
            - db
    db:
        image: mysql:8.0
        restart: always
        volumes:
            - /var/lib/${APP_NAME}/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8081:3306"
        container_name: project_db
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - "8082:80"
        container_name: phpmyadmin
        environment:
            UPLOAD_LIMIT: 300M